[project]
name = "disruptive-final"
authors = ["Core Wellness Team"]
description = "A blockchain-powered personal wellness tracking and motivation platform"
telemetry = false
requirements = []
[contracts.wellness-hub]
path = "contracts/wellness-hub.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
